### ISSUE TITLE
qrcode.html produces unscannable codes

### ISSUE THREAD

**Issue by dirkbike** [freeotp/freeotp.github.io#2]
QR codes generated by [qrcode.html](https://freeotp.github.io/qrcode.html) will not scan using the FreeOTP app.  I verified that the app was working correctly by scanning codes from [xanxys.net](http://www.xanxys.net/totp/).  Here's an example of a non-working code:
![image](https://cloud.githubusercontent.com/assets/3711678/25767763/546f7780-31ca-11e7-97aa-1687b9bbcf75.png)
Here's an example of a working code:
![image](https://cloud.githubusercontent.com/assets/3711678/25767785/77ccd2cc-31ca-11e7-98bf-acaf05ff5138.png)

**Comment by npmccallum** [comment]
I tested your input on the new website (now live). I was unable to reproduce the problem. If the problem still persists, feel free to reopen this bug.
