### ISSUE TITLE
Please add the manual token addition button and edit button again

### ISSUE THREAD

**Issue by kagaluga** [freeotp/freeotp.github.io#33]
Hi,
the edit button was very essential to add further information to Bad designed QR code’s from some sides. Even big known companies do not inkl use a username very often. Therefore it is essential that further information could be add to an token in order to have more than one user account (which is often needed; one for admin and one for general usage). 
Also some backups do only provide the key as string. No QR code included :-/

**Comment by SnakeHaveYou** [comment]
Some apps won’t give a QR Code, so the only way is to manually add the key to the app
