### ISSUE TITLE
Rename tokens

### ISSUE THREAD

**Issue by wehurlbert** [freeotp/freeotp.github.io#42]
It appears that the ability to rename tokens, and select images, has disappeared from the iOS app.  This greatly reduces the utility of the app.  What's going on?

**Comment by jekuno** [comment]
I'd also love to see that feature. I have two services which changed their name inbetween and it would help to have the correct names for quickly finding the corect tokens.

**Comment by conloos** [comment]
+1

**Comment by justin-stephenson** [comment]
If you touch the token icon, a pencil icon should appear in the above menu - press this pencil icon to edit the token label.

**Comment by justin-stephenson** [comment]
> Doesn't work for me. Touching the token icon (or the text next to the icon) in the iOS app simply generates a new token.

Could you please provide a screenshot, or video of this?

**Comment by jekuno** [comment]
The video doesn't show the tap unfortunately, but that's how it looks like, when I tap on the grey symbol on the left side:

https://user-images.githubusercontent.com/10961144/220406728-b697c97e-1efe-4c6e-8d56-8b6cd9088099.mov

**Comment by Neustradamus** [comment]
I confirm a new time the problem (we can not rename a token), and there is no possibility to change the icon too.

**Comment by justin-stephenson** [comment]
Sorry, I assumed we were talking about Android. Unfortunately iOS does not support changing the token name currently, I am open to adding this functionality however. PRs are welcome.

**Comment by Neustradamus** [comment]
@justin-stephenson: It has been solved?

**Comment by Neustradamus** [comment]
@justin-stephenson: Can you generate the new release with this fix?

Thanks in advance!

**Comment by justin-stephenson** [comment]
This should be filed against https://github.com/freeotp/freeotp-ios - I believe there is already an existing issue open for this in that repo.

**Comment by Neustradamus** [comment]
@justin-stephenson: It is better to transfer all iOS issues in the good repo, and Android issues in the good repo too!
