### ISSUE TITLE
Since Update App closes after start

### ISSUE THREAD

**Issue by MIZR1** [freeotp/freeotp.github.io#75]
Since your update yesterday FreeOTP closes immediately after start. So it doesn’t work anymore. Please fix it asap or restore last version. I need app for work so please do it asap.

Thx

**Comment by psjnek** [comment]
> Since your update yesterday FreeOTP closes immediately after start. So it doesn’t work anymore. Please fix it asap or restore last version. I need app for work so please do it asap.
> 
> Thx

The bug you described does not affect the website for FreeOTP. This issue should therefore be closed.
@justin-stephenson

**Comment by psjnek** [comment]
@justin-stephenson 
There are a bunch of other issues in this repo that do not affect the website itself. Could you maybe close them too?

**Comment by justin-stephenson** [comment]
@WebSnke Sure, if you can point out which ones that would be helpful.

**Comment by psjnek** [comment]
> @WebSnke Sure, if you can point out which ones that would be helpful.

Thanks for closing these issues:

- #1 
- #8 
- #9
- #10
- #11
- #12 
- #14 
- #15 
- #17 
- #20
- #23 
- #32 
- #33 
- #42 
- #43
