### ISSUE TITLE
New website design idea

### ISSUE THREAD

**Issue by psjnek** [freeotp/freeotp.github.io#76]
I am working on a new website for FreeOTP. This is what is currently looks like.

Light:
![image](https://github.com/freeotp/freeotp.github.io/assets/94064167/f4a51bff-b1b0-4bef-be87-eec18963e1b4)

Dark:
![image](https://github.com/freeotp/freeotp.github.io/assets/94064167/4d43634c-393d-47fe-b78c-c1ce9014c0b9)

@justin-stephenson
Let me know what you think about it and whether I should open a PR or not.

**Comment by psjnek** [comment]
[ deleted ]

**Comment by psjnek** [comment]
@npmccallum 
What do you think about it?

**Comment by psjnek** [comment]
@npmccallum @justin-stephenson 
Here is yet another updated version:

Dark:
![image](https://github.com/freeotp/freeotp.github.io/assets/94064167/f52acae4-7f95-499c-8528-67acf181d171)

Light:
![image](https://github.com/freeotp/freeotp.github.io/assets/94064167/3c7c1ce0-d8d5-4d73-908d-ca65f7ba3ff6)

**Comment by justin-stephenson** [comment]
@WebSnke I like the clean design, is it intended to replace https://freeotp.github.io/ ? If yes we will just need to link to other pages such as https://freeotp.github.io/ and the TOTP/HOTP RFCs.

Thanks!

-Justin

**Comment by psjnek** [comment]
Yeah, it's supposed to replace the old one.

**Comment by justin-stephenson** [comment]
> Yeah, it's supposed to replace the old one.

Okay great, I am happy to review a PR.

**Comment by psjnek** [comment]
> > Yeah, it's supposed to replace the old one.
> 
> Okay great, I am happy to review a PR.

Should I rewrite it in React? It is currently plain HTML with a bit of Bootstrap CSS. I would also make sure to use reusable headers and footers.

**Comment by psjnek** [comment]
It would also be great if you could provide a SVG of the logo and modern screenshots of the app.

**Comment by justin-stephenson** [comment]
Sure, I am okay building the page with React if that is your preference.

> It would also be great if you could provide a SVG of the logo and modern screenshots of the app.

Okay I will work on getting those to you.

**Comment by psjnek** [comment]
Could you maybe add a license to this project so that I can replace the RedHat copyright with the open-source license?

**Comment by psjnek** [comment]
@justin-stephenson 
Can you think of more features I could add to the website in the features section?
